#!/bin/env python3

import os
import sys
import json
import argparse
import subprocess
from random import randint

from time import time

RELAYS_LINK = "https://api.mullvad.net/www/relays/all/"
RELAYS_FILE = "/tmp/mulpingData"

TIMESTAMP_INDEX = 0

HOSTNAME = "hostname"
TYPE = "type"
ACTIVE = "active"
COUNTRY_CODE = "country_code"
COUNTRY_NAME = "country_name"
CITY_CODE = "city_code"
CITY_NAME = "city_name"
IPV4 = "ipv4_addr_in"
IPV6 = "ipv6_addr_in"
PROVIDER = "provider"
BANDWIDTH = "network_port_speed"
OWNED = "owned"
STBOOT = "stboot"
RTT = "round_trip_time"

WIREGUARD = "wireguard"
OPENVPN = "openvpn"
BRIDGE = "bridge"


#############################
# Relay filtering utilities #
#############################


# Returns a function that returns a function that tests
# if attribute 'a' in relay 'r' has value 'v'
eqAttr = lambda a: (lambda v: (lambda r: a in r and r[a] == v))

# Analogous
neqAttr = lambda a: (lambda v: (lambda r: a in r and r[a] != v))
geqAttr = lambda a: (lambda v: (lambda r: a in r and r[a] >= v))

# Returns a function that given a relay 'r', tests if it fits at least one of the conditions in 'filters'
filterOr = lambda filters: (lambda r: [f(r) for f in filters].count(True) > 0)

# Returns a function that given a relay 'r', tests if it fits all of the conditions in 'filters'
filterAnd = lambda filters: (lambda r: [f(r) for f in filters].count(False) == 0)


##################
# Error handling #
##################


def failure(err):
    print(err, file = sys.stderr)
    sys.exit(1)


#########################
# Relays data retrieval #
#########################


def fetchRelays():
    print("Fetching relays... ", end = "")
    sys.stdout.flush()

    # Only import the "requests" module here as it takes
    # significantly longer than the others
    import requests

    try:
        relays = requests.get(f"{RELAYS_LINK}").json()
    except:
        failure("Could not get relays")

    relays.insert(TIMESTAMP_INDEX, time())
    with open(RELAYS_FILE, "w") as f:
        json.dump(relays, f)
    del relays[TIMESTAMP_INDEX]

    print("done!\n")
    return relays

def loadRelays():
    with open(RELAYS_FILE, "r") as f:
        relays = json.loads(f.read())

    if not isinstance(relays[TIMESTAMP_INDEX], (float, int)):
        raise Exception

    # If the data is more than 12 hours old, fetch it again
    if time() - relays[TIMESTAMP_INDEX] >= 43200:
        raise Exception

    # Delete timestamp from final relay list
    del relays[TIMESTAMP_INDEX]

    return relays

def getRelays():
    if os.path.isfile(RELAYS_FILE):
        try:
            relays = loadRelays()
        except:
            relays = fetchRelays()
    else:
        relays = fetchRelays()

    return relays


##################
# Ping utilities #
##################


def parsePing(pingOutput):
    resultsLine = pingOutput.splitlines()[pingOutput.count("\n") - 1]

    if not resultsLine.startswith("rtt"):
        return None, None, None

    rtts = [float(v) for v in resultsLine.split(" ")[3].split("/")]

    return rtts[0], rtts[1], rtts[2]

def ping(addr, count, timeout = 10, ipv6 = False):
    try:
        # e.g.: ping 0.0.0.0 -nqc1 -W10
        pingCommand = ["ping", addr, "-nqc", str(count), "-W", str(timeout)]
        if ipv6: pingCommand.append("-6")

        pingProcess = subprocess.run(pingCommand, capture_output = True)
    except:
        failure("The `ping` program could not be called")

    if pingProcess.returncode != 0:
        return None, None, None

    return parsePing(pingProcess.stdout.decode())


#####################
# Mullvad utilities #
#####################


def mullvadChangeRelay(hostname):
    try:
        mullvadProcess = subprocess.run(["mullvad", "relay", "set", "hostname", hostname])

        if mullvadProcess.returncode != 0:
            raise Exception
    except:
        failure(f"An error occurred while trying to change the Mullvad relay options to hostname {hostname}")


######################
# Printing utilities #
######################


noFormat = lambda i: i
noPrint = lambda *_: None

relayTypeFormat = {
    WIREGUARD: "WireGuard",
    OPENVPN: "OpenVPN",
    BRIDGE: "Bridge"
}

ITEMS_FORMAT = {
    HOSTNAME: noFormat,
    IPV4: noFormat,
    IPV6: noFormat,
    COUNTRY_CODE: noFormat,
    CITY_CODE: noFormat,
    PROVIDER: noFormat,
    RTT: lambda rtt: f"{rtt:.3f}ms",
    OWNED: lambda o: "Owned" if o else "Rented",
    BANDWIDTH: lambda b: f"{b} Gbps",
    COUNTRY_NAME: noFormat,
    CITY_NAME: noFormat,
    STBOOT: lambda s: "RAM" if s else "Disk",
    TYPE: lambda t: relayTypeFormat[t] if t in relayTypeFormat else "Unknown"
}

ITEMS_IDS = {
    "h": HOSTNAME,
    "4": IPV4,
    "6": IPV6,
    "c": COUNTRY_CODE,
    "C": CITY_CODE,
    "p": PROVIDER,
    "l": RTT,
    "O": OWNED,
    "b": BANDWIDTH,
    "cf": COUNTRY_NAME,
    "Cf": CITY_NAME,
    "s": STBOOT,
    "t": TYPE
}

attributesShort = [HOSTNAME, RTT]
attributesLong = [HOSTNAME, RTT, COUNTRY_NAME, CITY_NAME, PROVIDER, OWNED, STBOOT]

def getAttributes(formatList):
    attributes = []
    for id in formatList:
        if id not in ITEMS_IDS:
            failure(f"Unknown attribute identifier: {id}")

        attributes.append(ITEMS_IDS[id])

    return attributes

def getSpacing(relays, items):
    spaces = {}
    singleItemSpace = lambda i: (lambda r: len(ITEMS_FORMAT[i](r[i])))

    for item in items:
        if item == RTT: continue
        spaces[item] = singleItemSpace(item)(max(relays, key = singleItemSpace(item)))

    spaces[RTT] = 10
    return spaces

getSpacingList = lambda i, spacing: [spacing[item] if item in spacing else None for item in i]

def printBox(items, start, end, middle, regular):
    if items == []: return ""

    box = start
    for i in items:
        box += regular * (i + 2) + middle

    box = box[0:len(box) - 1] + end

    print(box)

def printResult(relay, attributes, itemsSpaces, wall):
    print(f"{wall}", end = "")
    for attribute in attributes:
        if not attribute in itemsSpaces or attribute not in ITEMS_FORMAT:
            failure("Unknown attribute received by printing function")

        if relay[attribute] == None:
            print(f" {'error':{itemsSpaces[attribute]}} {wall}", end = "")
        else:
            print(f" {ITEMS_FORMAT[attribute](relay[attribute]):{itemsSpaces[attribute]}} {wall}", end = "")

    print()


########
# Main #
########


parser = argparse.ArgumentParser(
    prog = "mulping",
    description = "Batch pings utility for Mullvad VPN (not affiliated)",
)

relayConditions = [
    neqAttr(TYPE)(BRIDGE),
    eqAttr(ACTIVE)(True)
]

parser.add_argument("-c", "--country", action = "store", help = "Only select servers located in the countries specified", nargs = "+", metavar = "country_code")
parser.add_argument("-cn", "--country-not", action = "store", help = "Exclude servers located in the countries specified", nargs = "+", metavar = "country_code")
parser.add_argument("-C", "--city", action = "store", help = "Only select servers located in the cities specified", nargs = "+", metavar = "city_code")
parser.add_argument("-Cn", "--city-not", action = "store", help = "Exclude servers located in the cities specified", nargs = "+", metavar = "city_code")
parser.add_argument("-p", "--provider", action = "store", help = "Only select servers using the specified providers", nargs = "+", metavar = "provider")
parser.add_argument("-pn", "--provider-not", action = "store", help = "Exclude servers using the specified providers", nargs = "+", metavar = "provider")
parser.add_argument("-f", "--format", action = "store", help = "Specify the relay attributes to print in the results", nargs = "+", metavar = "identifier")
parser.add_argument("-v", "--verbose", action = "store_true", help = "Show more relay attributes in the results")
parser.add_argument("-w", "--wireguard", action = "store_true", help = "Only select WireGuard servers")
parser.add_argument("-o", "--openvpn", action = "store_true", help = "Only select OpenVPN servers")
parser.add_argument("-s", "--stboot", action = "store_true", help = "Only select stboot servers")
parser.add_argument("-O", "--owned", action = "store_true", help = "Only select servers owned by Mullvad")
parser.add_argument("-b", "--bandwidth", action = "store", help = "Only select servers that have at least this bandwidth speed (Gbps)", metavar = "bandwidth")
parser.add_argument("-t", "--timeout", action = "store", help = "Maximum time to wait for each ping response", metavar = "timeout")
parser.add_argument("-6", "--ipv6", action = "store_true", help = "Use IPv6 to ping servers (requires IPv6 connectivity on both ends)")
parser.add_argument("-u", "--use", action = "store_true", help = "Change Mullvad relay options to use the lowest latency server tested")
parser.add_argument("-r", "--random", action = "store_true", help = "Don't test latency and just change Mullvad relay options to use a random server within the ones available based on the other arguments")
parser.add_argument("-q", "--quiet", action = "store_true", help = "Don't show relay results box")

args = parser.parse_args()

if args.format:
    attributes = getAttributes(args.format)
else:
    attributes = attributesLong if args.verbose else attributesShort

pingRequested = RTT in attributes

if args.random:
    while RTT in attributes: attributes.remove(RTT)

    pingRequested = False

if args.use and not pingRequested and not args.random:
    failure("Use a format that contains latency to use the '-u' option")

if args.country != None:
	countryConditions = list(map(eqAttr(COUNTRY_CODE), args.country))

	countryFilter = filterOr(countryConditions)	
	relayConditions.append(countryFilter)

if args.country_not != None:
	notCountryConditions = list(map(neqAttr(COUNTRY_CODE), args.country_not))

	notCountryFilter = filterAnd(notCountryConditions)	
	relayConditions.append(notCountryFilter)

if args.city != None:
    cities = list(zip(args.city[::2], args.city[1::2]))
    
    # Returns a function that tests if relay 'r' is in the city defined by the tuple 'cityTuple'
    # cityTuple[0] -> country code
    # cityTuple[1] -> city code
    inCity = lambda cityTuple: (lambda r: eqAttr(COUNTRY_CODE)(cityTuple[0])(r) and eqAttr(CITY_CODE)(cityTuple[1])(r))

    cityConditions = list(map(inCity, cities))

    cityFilter = filterOr(cityConditions)
    relayConditions.append(cityFilter)

if args.city_not != None:
    notCities = list(zip(args.city_not[::2], args.city_not[1::2]))

    # Symmetrical to inCity
    notInCity = lambda cityTuple: (lambda r: not (eqAttr(COUNTRY_CODE)(cityTuple[0])(r) and eqAttr(CITY_CODE)(cityTuple[1])(r)))

    notCityConditions = list(map(notInCity, notCities))

    notCityFilter = filterAnd(notCityConditions)
    relayConditions.append(notCityFilter)

if args.provider != None:
	providerConditions = list(map(eqAttr(PROVIDER), args.provider))

	providerFilter = filterOr(providerConditions)	
	relayConditions.append(providerFilter)

if args.provider_not != None:
	notProviderConditions = list(map(neqAttr(PROVIDER), args.provider_not))

	notProviderFilter = filterAnd(notProviderConditions)	
	relayConditions.append(notProviderFilter)

if args.bandwidth:
  try:
    relayConditions.append(geqAttr(BANDWIDTH)(float(args.bandwidth)))
  except:
    failure("Error: the bandwidth option must be a number")

if args.wireguard: relayConditions.append(eqAttr(TYPE)(WIREGUARD))
if args.openvpn: relayConditions.append(eqAttr(TYPE)(OPENVPN))
if args.stboot: relayConditions.append(eqAttr(STBOOT)(True))
if args.owned: relayConditions.append(eqAttr(OWNED)(True))
if args.ipv6: relayConditions.append(lambda r: IPV6 in r)

timeout = 10 if args.timeout == None else float(args.timeout) / 1000
IP = IPV6 if args.ipv6 else IPV4
boxPrint = noPrint if args.quiet else printBox
linePrint = noPrint if args.quiet else printResult

relays = list(filter(filterAnd(relayConditions), getRelays()))

if relays == []:
    failure("The conditions specified resulted in no relays")

itemsSpaces = getSpacing(relays, attributes)


boxPrint(getSpacingList(attributes, itemsSpaces), "┌", "┐", "┬", "─")
for index, r in enumerate(relays):
    host = r[HOSTNAME]
    address = r[IP]

    if pingRequested:
        _, rtt, _ = ping(address, 1, timeout = timeout, ipv6 = args.ipv6)
        relays[index][RTT] = rtt

    linePrint(r, attributes, itemsSpaces, "│")
boxPrint(getSpacingList(attributes, itemsSpaces), "└", "┘", "┴", "─")
if not args.quiet: print()

if args.random:
    mullvadChangeRelay(relays[randint(0, len(relays) - 1)][HOSTNAME])

if not pingRequested:
    sys.exit(0)

# Filter out relays whose latency test resulted resulted in an error
relays = list(filter(lambda r: r[RTT] != None, relays))

if relays == []:
    failure("No relay could be reached")

lowestLatency = min(relays, key = lambda r: r[RTT])
maxLatency = max(relays, key = lambda r: r[RTT])

print(f"Highest latency host: {maxLatency[HOSTNAME]} ({maxLatency[RTT]}ms)")
print(f"Lowest latency host: {lowestLatency[HOSTNAME]} ({lowestLatency[RTT]}ms)")

if args.use:
    print()
    mullvadChangeRelay(lowestLatency[HOSTNAME])
